export const personal = {
  name:        "Ernest Mpiani",
  title:       "Computer Engineering Student",
  tagline:     "Backend Developer · Data Scientist · Virtual Assistant",
  university:  "KNUST, Ghana",
  year:        "3rd Year",
  email:       "ernestmpiani15@gmail.com",
  github:      "https://github.com/Ernesto11524",
  linkedin:    "https://linkedin.com/in/ernest524",
  formspreeId: "mzdkyboy",
  bio: [
    "I'm a 3rd-year Computer Engineering student at KNUST, Ghana, building at the intersection of backend systems, data science, and intelligent automation.",
    "I write clean, scalable backend code, extract insights from complex datasets, and help people work smarter through virtual assistance. Every project I ship is a step toward building technology that actually matters.",
    "When I'm not coding, I'm learning — always. The field moves fast and I move with it.",
  ],
  roles: ["Backend Developer", "Data Scientist", "Virtual Assistant", "Computer Engineer"],
};

export const skills = [
  { category: "Backend",            items: ["Python", "Node.js", "REST APIs", "PostgreSQL", "MongoDB", "Django"] },
  { category: "Data Science",       items: ["Pandas", "NumPy", "Scikit-learn", "Matplotlib", "Jupyter", "SQL"] },
  { category: "Tools",              items: ["Git", "Docker", "Linux", "VS Code", "Postman", "Vercel"] },
  { category: "Currently Learning", items: ["FastAPI", "Machine Learning", "AWS", "System Design"] },
];

export const projects = [
  {
    id: 1,
    title: "API Gateway Service",
    description: "A scalable REST API gateway built with Node.js handling authentication, rate limiting, and request routing for microservice architecture.",
    tech: ["Node.js", "Express", "Redis", "PostgreSQL"],
    status: "Completed",
    github: "#",
    live: null,
  },
  {
    id: 2,
    title: "Sales Data Analyzer",
    description: "Python pipeline that ingests, cleans, and visualizes large retail datasets — surfacing key business insights with automated reporting.",
    tech: ["Python", "Pandas", "Matplotlib", "Jupyter"],
    status: "Completed",
    github: "#",
    live: null,
  },
  {
    id: 3,
    title: "Smart Task Automator",
    description: "A virtual assistant workflow tool that automates repetitive tasks — scheduling, email triage, and file organization — saving hours per week.",
    tech: ["Python", "Google APIs", "Zapier", "Notion API"],
    status: "In Progress",
    github: "#",
    live: null,
  },
  {
    id: 4,
    title: "Student Resource Portal",
    description: "Full-stack web app for KNUST students to share notes, past questions, and study resources.",
    tech: ["Django", "PostgreSQL", "HTML/CSS", "JavaScript"],
    status: "In Progress",
    github: "#",
    live: null,
  },
];

export const certifications = [
  {
    id: 1,
    title: "Backend Development Certification",
    issuer: "ALX",
    date: "2025",
    description: "Comprehensive certification covering server-side development, APIs, databases, and deployment.",
    badge: "01",
    link: "https://drive.google.com/file/d/16MjYz60vhCTtKVX2JEF9mUTRY3bLagKX/view?usp=sharing",
  },
  {
    id: 2,
    title: "Data Science Professional Certificate",
    issuer: "ALX",
    date: "2026",
    description: "End-to-end data science workflow: data wrangling, visualization, machine learning, and deployment.",
    badge: "02",
    link: "https://drive.google.com/file/d/12CBSGD1eopsrnW2YTHedUUOZIW9hFUqD/view?usp=sharing",
  },
  {
    id: 3,
    title: "Virtual Assistant Certification",
    issuer: "ALX",
    date: "2024",
    description: "Professional virtual assistance skills — project management, communication, and digital tools mastery.",
    badge: "03",
    link: "https://drive.google.com/file/d/16QEtueoKEplLL8m7ft3ErGVemZ5VA8QR/view?usp=sharing",
  },
  {
    id: 4,
    title: "AI Career Essentials",
    issuer: "ALX",
    date: "2024",
    description: "Comprehensive program covering the fundamentals of artificial intelligence, prompt engineering, and how to leverage AI tools effectively in a professional environment. Topics included AI literacy, ChatGPT and generative AI workflows, AI-assisted productivity, and navigating the future of work in an AI-driven world.",
    badge: "04",
    link: "https://drive.google.com/file/d/15pp4jRrSsfBI6YH-whtT--kgi93GKaOB/view?usp=sharing",
  },
  {
    id: 5,
    title: "Professional Foundations",
    issuer: "ALX",
    date: "2025",
    description: "A rigorous professional development program building the core skills needed to thrive in the modern workplace. Covered communication, critical thinking, personal branding, teamwork, time management, problem-solving frameworks, and navigating remote and hybrid work environments.",
    badge: "05",
    link: "https://drive.google.com/file/d/1i9hE_W98F8dmzXZOBGTmEjsYQs0vpLei/view?usp=sharing",
  },
  {
    id: 6,
    title: "Python for Data Science",
    issuer: "ALX",
    date: "2025",
    description: "Hands-on certification in Python programming applied to data science workflows. Topics covered include Python fundamentals, data manipulation with Pandas and NumPy, data visualization with Matplotlib and Seaborn, working with APIs and datasets, and an introduction to machine learning concepts with Scikit-learn.",
    badge: "06",
    link: "https://drive.google.com/file/d/1UySVtjNcHQey_BSlJknatQ9-58riVuaw/view?usp=sharing",
  },
];
